name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable          

      - name: Jq commit mesg
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" | jq .event.commits[].message
        
      - name: Cache cross
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cargo/bin/cross
          key: cross1
        
      - name: setting up var URL
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          URL=$(echo $GITHUB_CONTEXT | jq .event.commits[].message) 
          URL="${URL%\"}"
          URL="${URL#\"}"
          echo URL=$URL >> $GITHUB_ENV
     
      - name: setting up var NAME
        run: |
          NAME=$(echo $URL | awk -F "/" '{ print $5 }' ) 
          echo NAME=$NAME >> $GITHUB_ENV

      - name: git clone and cross compile
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: | # if windows, don't forget to add .exe in the upload
          git clone $URL
          cd $NAME
          cross build --target x86_64-pc-windows-gnu --release

      - uses: actions/upload-artifact@v2
        with:
          name: ${{env.NAME}}-win-release
          path: ${{env.NAME}}/target/x86_64-pc-windows-gnu/release/${{env.NAME}}.exe
      
